# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import enclave_pb2 as enclave__pb2


class enclaveStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.schedule = channel.unary_unary(
                '/rpc.enclave/schedule',
                request_serializer=enclave__pb2.SchedulingRequest.SerializeToString,
                response_deserializer=enclave__pb2.SchedulingResponse.FromString,
                )


class enclaveServicer(object):
    """Missing associated documentation comment in .proto file."""

    def schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_enclaveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.schedule,
                    request_deserializer=enclave__pb2.SchedulingRequest.FromString,
                    response_serializer=enclave__pb2.SchedulingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.enclave', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class enclave(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.enclave/schedule',
            enclave__pb2.SchedulingRequest.SerializeToString,
            enclave__pb2.SchedulingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
