FROM bl4ck5un/dcnet-builder
MAINTAINER Fan Zhang <bl4ck5unxx@gmail.com>

ARG GRPC_PREFIX=/opt/grpc
ADD . /src
WORKDIR /root

RUN cmake /src -DGRPC_PREFIX=$GRPC_PREFIX && \
    make -j $(nproc) && \
    rm -rf src

ENV SGX_SDK=/opt/intel/sgxsdk
ENV LD_LIBRARY_PATH=$SGX_SDK/sdk_libs

EXPOSE 12345
ENTRYPOINT ./main